cc/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^$', TemplateView.as_view(template_name='home.html')),
    (r'^map/$', TemplateView.as_view(template_name='map.html')),
    (r'^about/$', TemplateView.as_view(template_name='about.html')),
    (r'^help/$', TemplateView.as_view(template_name='help.html')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('drinker.urls')),
)

drinker/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
     url(r'^register/$', 'drinker.views.DrinkerRegistration'),
     url(r'^login/$', 'drinker.views.LoginRequest'),
     url(r'^logout/$', 'drinker.views.LogoutRequest'),
     (r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done'),
     (r'^resetpassword/$', 'django.contrib.auth.views.password_reset'),
     (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
     (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
     url(r'^settings/$', 'drinker.views.user_settings'),
     url(r'^profile/$', 'drinker.views.user_profile'),
)

drinker/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
# Create your models here.

class Drinker(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=100)
    birthday = models.DateField()
    bio = models.TextField(max_length=140)
    website = models.CharField(max_length=100)
    location = models.CharField(max_length=200)


    def __unicode__(self):
        return self.name


def create_drinker_user_callback(sender, instance, **kwargs):
    drinker, new = Drinker.objects.get_or_create(user=instance)
    post_save.connect(create_drinker_user_callback, User)

home/models.py
from django.db import models

# Create your models here.

wmap/models.py
from django.db import models

# Create your models here.

drinker/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from models import Drinker

class RegistrationForm(ModelForm):
        username = forms.CharField(label=(u'User Name'))
        email = forms.EmailField(label=(u'Email Address'))
        password = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False))
        password1 = forms.CharField(label=(u'Verify Password'), widget=forms.PasswordInput(render_value=False))

        class Meta:
                model = Drinker
                exclude = ('user',)

        def clean_username(self):
                username = self.cleaned_data['username']
                try:
                        User.objects.get(username=username)
                except User.DoesNotExist:
                        return username
                raise forms.ValidationError("That username is already taken, please select another.")

        def clean(self):
                if self.cleaned_data['password'] != self.cleaned_data['password1']:
                        raise forms.ValidationError("The passwords did not match.  Please try again.")
                return self.cleaned_data

class LoginForm(forms.Form):
        username        = forms.CharField(label=(u'User Name'))
        password        = forms.CharField(label=(u'Password'), widget=forms.PasswordInput(render_value=False))

class EditProfileForm(forms.ModelForm):

    class Meta:
        model = Drinker
        fields = ('name', 'bio', 'birthday', 'location', 'website')

drinker/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.template import RequestContext
from forms import RegistrationForm, LoginForm
from models import Drinker
from forms import EditProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.core.context_processors import csrf

def DrinkerRegistration(request):
        if request.user.is_authenticated():
                return HttpResponseRedirect('/')
        if request.method == 'POST':
                form = RegistrationForm(request.POST)
                if form.is_valid():
                        user = User.objects.create_user(username=form.cleaned_data['username'], email = form.cleaned_data['email'], password = form.cleaned_data['password'])
                        user.save()
                        drinker = Drinker(user=user, name=form.cleaned_data['name'], birthday=form.cleaned_data['birthday'])
                        drinker.save()
                        return HttpResponseRedirect('/')
                else:
                        return render_to_response('register.html', {'form': form}, context_instance=RequestContext(request))
        else:
                ''' user is not submitting the form, show them a blank registration form '''
                form = RegistrationForm()
                context = {'form': form}
                return render_to_response('register.html', context, context_instance=RequestContext(request))

def LoginRequest(request):
        if request.user.is_authenticated():
                return HttpResponseRedirect('/')
        if request.method == 'POST':
                form = LoginForm(request.POST)
                if form.is_valid():
                        username = form.cleaned_data['username']
                        password = form.cleaned_data['password']
                        drinker = authenticate(username=username, password=password)
                        if drinker is not None:
                                login(request, drinker)
                                return HttpResponseRedirect('/')
                        else:
                                return render_to_response('login.html', {'form': form}, context_instance=RequestContext(request))
                else:
                        return render_to_response('login.html', {'form': form}, context_instance=RequestContext(request))
        else:
                form = LoginForm()
                context = {'form': form}
                return render_to_response('login.html', context, context_instance=RequestContext(request))

def LogoutRequest(request):
        logout(request)
        return HttpResponseRedirect('/')


@login_required
def user_settings(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user.drinker)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/u/%s' % request.user.username)
    else:
        form = EditProfileForm(instance=request.user.drinker)

    args = {}
    args.update(csrf(request))

    args['form'] = form

    return render_to_response('settings.html', args, context_instance=RequestContext(request))

@login_required
def user_profile(request):

    args = {}
    args.update(csrf(request))

    args['thisuser'] = Drinker.objects.get(user=request.user.drinker)

    return render_to_response('profile.html', args, context_instance=RequestContext(request))

home/views.py
# Create your views here.

wmap/views.py
# Create your views here.

drinker/templates/login.html
{% extends "base.html" %}
{% block title %}
<div class="icon login"></div>
<a id="notthis" title="Currentpage">Login</a>
{% endblock%}
{% block content %}
<div class="prof_place">
<form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="register_div">
        {% if form.username.errors %}<p class="error">{{ form.username.errors }}</p>{% endif %}
        <p><label for="username"{% if form.username.errors %} class="error"{% endif %}>Username:</label></p>
        <p>{{ form.username }}</p>
</div>
<div class="register_div">
        {% if form.password.errors %}<p class="error">{{ form.password.errors }}</p>{% endif %}
        <p><label for="password"{% if form.password.errors %} class="error"{% endif %}>Password:</label></p>
        <p>{{ form.password }}</p>
</div>
<p><input type="submit" alt="register" /></p>
</form>
<p>Forgot your password? <a href="/accounts/resetpassword/">Reset it!</a></p>
</div>
{% endblock %}

drinker/templates/password_change_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{% trans 'Password change successful' %}{% endblock %}

{% block content %}

<h1>{% trans 'Password change successful' %}</h1>

<p>{% trans 'Your password was changed.' %}</p>

{% endblock %}

drinker/templates/password_change_form.html
{% extends "admin/base_site.html" %}
{% load i18n static %}
{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %} {% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{% trans 'Password change' %}{% endblock %}

{% block content %}<div id="content-main">

<form action="" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="errornote">
    {% blocktrans count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
    </p>
{% endif %}

<h1>{% trans 'Password change' %}</h1>

<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

<fieldset class="module aligned wide">

<div class="form-row">
    {{ form.old_password.errors }}
    <label for="id_old_password" class="required">{% trans 'Old password' %}:</label>{{ form.old_password }}
</div>

<div class="form-row">
    {{ form.new_password1.errors }}
    <label for="id_new_password1" class="required">{% trans 'New password' %}:</label>{{ form.new_password1 }}
</div>

<div class="form-row">
{{ form.new_password2.errors }}
    <label for="id_new_password2" class="required">{% trans 'Password (again)' %}:</label>{{ form.new_password2 }}
</div>

</fieldset>

<div class="submit-row">
    <input type="submit" value="{% trans 'Change my password' %}" class="default" />
</div>

<script type="text/javascript">document.getElementById("id_old_password").focus();</script>
</div>
</form></div>

{% endblock %}

drinker/templates/password_reset_complete.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{% trans 'Password reset complete' %}{% endblock %}

{% block content %}

<h1>{% trans 'Password reset complete' %}</h1>

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

drinker/templates/password_reset_confirm.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset confirmation' %}
</div>
{% endblock %}

{% block title %}{% trans 'Password reset' %}{% endblock %}

{% block content %}

{% if validlink %}

<h1>{% trans 'Enter new password' %}</h1>

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form action="" method="post">{% csrf_token %}
{{ form.new_password1.errors }}
<p class="aligned wide"><label for="id_new_password1">{% trans 'New password:' %}</label>{{ form.new_password1 }}</p>
{{ form.new_password2.errors }}
<p class="aligned wide"><label for="id_new_password2">{% trans 'Confirm password:' %}</label>{{ form.new_password2 }}</p>
<p><input type="submit" value="{% trans 'Change my password' %}" /></p>
</form>

{% else %}

<h1>{% trans 'Password reset unsuccessful' %}</h1>

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}

{% endblock %}

drinker/templates/password_reset_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{% trans 'Password reset successful' %}{% endblock %}

{% block content %}

<h1>{% trans 'Password reset successful' %}</h1>

<p>{% trans "We've emailed you instructions for setting your password to the email address you submitted. You should be receiving it shortly." %}</p>

{% endblock %}

drinker/templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'django.contrib.auth.views.password_reset_confirm' uidb36=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

drinker/templates/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}

<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>

{% block title %}{% trans "Password reset" %}{% endblock %}

{% block content %}

<h1>{% trans "Password reset" %}</h1>

<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form action="" method="post">{% csrf_token %}
{{ form.email.errors }}
<p><label for="id_email">{% trans 'Email address:' %}</label> {{ form.email }} <input type="submit" value="{% trans 'Reset my password' %}" /></p>
</form>

{% endblock %}

drinker/templates/profile.html
{% extends "base.html" %}

{% block title %}
    <div class="icon login"></div>
    <a id="notthis" title="Currentpage">{{ user }}</a>
{% endblock%}

{% block extra%}
{% endblock %}

{% block content %}
<div class="prof_page" >

</div>
<div class="prof_place">

    <a style="font:30px Arial;color:#555;font-weight: bold">{{ user }}</a> <a style="font:20px Arial;color:#555">{{ thisuser.name }}</a>

</div>
{% endblock %}

drinker/templates/register.html
{% extends "base.html" %}
{% block title %}
<div class="icon login"></div>
<a id="notthis" title="Currentpage">Register</a>
{% endblock%}
{% block extrahead %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js" type="text/javascript"></script>
        <script>
        $(function() {
                $( "#id_birthday" ).datepicker();
        });
        </script>
{% endblock %}
{% block content %}
<div class="prof_place">
    <form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="register_div">
        {% if form.username.errors %}<p class="error">{{ form.username.errors }}</p>{% endif %}
        <p><label for="username"{% if form.username.errors %} class="error"{% endif %}>Username:</label></p>
        <p>{{ form.username }}</p>
</div>
<div class="register_div">
        {% if form.email.errors %}<p class="error">{{ form.email.errors }}</p>{% endif %}
        <p><label for="email"{% if form.email.errors %} class="error"{% endif %}>Email:</label></p>
        <p>{{ form.email }}</p>
</div>
<div class="register_div">
        {% if form.password.errors %}<p class="error">{{ form.password.errors }}</p>{% endif %}
        <p><label for="password"{% if form.password.errors %} class="error"{% endif %}>Password:</label></p>
        <p>{{ form.password }}</p>
</div>
<div class="register_div">
        {% if form.password1.errors %}<p class="error">{{ form.password1.errors }}</p>{% endif %}
        <p><label for="password1"{% if form.password1.errors %} class="error"{% endif %}>Verify Password:</label></p>
        <p>{{ form.password1 }}</p>
</div>
<div class="register_div">
        {% if form.birthday.errors %}<p class="error">{{ form.birthday.errors }}</p>{% endif %}
        <p><label for="birthday"{% if form.birthday.errors %} class="error"{% endif %}>Birthday:</label></p>
        <p>{{ form.birthday }}</p>
</div>
<div class="register_div">
        {% if form.name.errors %}<p class="error">{{ form.name.errors }}</p>{% endif %}
        <p><label for="name"{% if form.name.errors %} class="error"{% endif %}>Name:</label></p>
        <p>{{ form.name }}</p>
</div>
<p><input type="submit" alt="register" /></p>
</form>
</div>
{% endblock %}

drinker/templates/settings.html
{% extends "base.html" %}

{% block content %}

  <h2>Edit profile - {{ user.username }}</h2>

  {% for field in form %}

        {{field.error}}

  {% endfor %}


  <form action="/accounts/settings/" method="post">{% csrf_token %}
  {{form.as_p}}

  <input type="submit" value="Update" />

  </form>

{% endblock %}

home/templates/home.html
{% extends "base.html" %}

{% block title %}
    <div class="icon home"></div>
    <a id="notthis" title="Currentpage">Home</a>
{% endblock%}

{% block extra%}
        <script>
            $('.header').css('background-color', 'transparent');
            /*
            var jsonfile = 'static/assets/js/';
            var myArr = [];
            $.getJSON(jsonfile + 'cons.json' , function(data){
                for(var j in data){
                    console.log(j + ': '+ data[j][0] + ' - ' + data[j][1] + ' - ' + data[j][2] );
                    var addressField = data[j][3];
                    var geocoder = new google.maps.Geocoder();
                    geocoder.geocode(
                            {'address': addressField},
                            function(results, status) {
                                if (status == google.maps.GeocoderStatus.OK) {
                                    var loc = results[0].geometry.location;
                                    console.log(loc.lat() + ', ' + loc.lng());
                                    // use loc.lat(), loc.lng()
                                }
                                else {
                                    console.log("Not found: " + status);
                                }
                            }
                    );
                }
            });*/

            $(function() {
                $('#mylist2').listplus({'sortBy':['.dateday']}, {'sortBy':['.datemonth']}, {'sortBy':['.dateyear']});
            });
        </script>
{% endblock %}

{% block content %}
        <div id="homee">
            <div style="text-align: center;padding-top:150px;color:#fff">
                <a style="font:50px Segoe UI Light;">GET</a><a style="font:50px Segoe UI;font-weight: bold">READY</a><br/><br/>
                <div style="background-color: rgba(255,255,255,0.6);padding:7px;width:300px;margin:0 auto;">
                    <a style="font:50px Segoe UI Light;">TO</a> <a style="font:50px Segoe UI Light;">EXPLORE</a>
                </div>
                <br/>
                <a style="font:50px Segoe UI Light;">BEST</a><a style="font:50px Segoe UI;font-weight: bold">CONVENTIONS</a>
            </div>
        </div>
        <div class="home_conts">
            <ul id="mylist2">

            </ul>
        </div>
{% endblock %}

templates/about.html
{% extends "base.html" %}

{% block title %}
    <div class="icon about"></div>
    <a id="notthis" title="Currentpage">About</a>
{% endblock%}

{% block content %}

{% endblock %}

templates/base.html
{% load static %}
<!Doctype html>
<html>
    <head>
        <title>
            The site
        </title>
        <link rel="stylesheet" type="text/css" href="{% static 'assets/css/main.css' %}"/>
        <script src="{% static 'assets/js/jquery.js' %}"></script>
        <script src="{% static 'assets/js/jquery-1.9.1.js' %}"></script>
        <script src="{% static 'assets/js/jquery-ui-1.10.3.custom.js' %}"></script>

        <script src="{% static 'assets/js/jquery.listplus.js' %}"></script>
        <script src="{% static 'assets/js/some.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
        <script src="{% static 'assets/js/mapp.js' %}"></script>

    </head>
    <body>
        {% block header %}
        <div class="header" >
            <div id="topmenu">
                {% block title %}

                {% endblock%}
                <ul id="menulist" class="option_act">
                    <li>
                        <div class="icon home"></div>
                        <a href="/" title="Home">Home</a>
                    </li>
                    <li>
                        <div class="icon map"></div>
                        <a href="/map" title="Map">Map</a>
                    </li>
                    <li>
                        <div class="icon about"></div>
                        <a href="/about" title="About">About</a>
                    </li>
                    <li>
                        <div class="icon help"></div>
                        <a href="/help" title="Help">Help</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <div class="icon login"></div>
                        <a href="/accounts/profile" title="Profile">{{ user }}</a>
                    </li>
                    <li>
                        <div class="icon logout"></div>
                        <a href="/accounts/logout" title="Login">Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <div class="icon login"></div>
                        <a href="/accounts/login" title="Login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            {% block extra%}

            {% endblock %}
        </div>
        {% endblock %}
        <div class="content">
            {% block content %}



            {% endblock %}
        </div>
        <input  id="static_files_url" type="hidden" value="{% static 'assets/'%}"/>
    </body>
</html>

templates/help.html
{% extends "base.html" %}

{% block title %}
    <div class="icon help"></div>
    <a id="notthis" title="Currentpage">Help</a>
{% endblock%}

{% block content %}

{% endblock %}

wmap/templates/map.html
{% extends "base.html" %}

{% block title %}
    <div class="icon map"></div>
    <a id="notthis" title="Currentpage">Map</a>
{% endblock%}

{% block extra%}
<div id="topmenu" class="opnthis" style="float:right;">
    <div class="icon marker"></div>
    <a id="notthis" style="padding-left:40px;">Con List</a>
</div>
{% endblock %}

{% block content %}
<script >
$(function() {
	$('#mylist').listplus({'sortBy':['.dateday']}, {'sortBy':['.datemonth']}, {'sortBy':['.dateyear']});

	$('#side_bar a').on('click',function(event) {
		$('.ui-active').removeClass('ui-active');
		$(this).addClass('ui-active');
	});

    $('#allin').on('click',function(event) {
		$('#mylist').listplus('destroy');
		$('#mylist').listplus({'sortBy':['.num']});
	});
    $('#animefilter').on('click',function(event) {
		$('#mylist').listplus('destroy');
		$('#mylist').listplus({'filterBy':['.Anime']});
	});
    $('#comixfilter').on('click',function(event) {
		$('#mylist').listplus('destroy');
		$('#mylist').listplus({'filterBy':['.Comix']});
	});
    $('#gamingfilter').on('click',function(event) {
		$('#mylist').listplus('destroy');
		$('#mylist').listplus({'filterBy':['.Gaming']});
	});

    $('#alphabetsort').on('click',function(event) {
		$('#mylist').listplus('destroy');
		$('#mylist').listplus({'sortBy':['.title']});
	});

	$('#upcomingsort').on('click',function(event) {
		$('#mylist').listplus('destroy');
		$('#mylist').listplus({'sortBy':['.dateday']}, {'sortBy':['.datemonth']}, {'sortBy':['.dateyear']});
	});
    var stat_f_url = $('#static_files_url').val();
    var thislogo = "url('" + stat_f_url + "img2/concavelogo2.png')";
    $('.header').css('background-image', thislogo );
});
</script>
<div id="mainmap" ></div>
<div id="side_bar"  >
    <div style="margin-bottom:10px">
        <a id="upcomingsort">Upcoming</a>
        <a id="allin">All</a>
        <a id="animefilter">Anime</a>
        <a id="comixfilter">Comix</a>
        <a id="gamingfilter">Gaming</a>
        <a id="alphabetsort">Alphabeticaly</a>
    </div>
    <ul id="mylist">

    </ul>
</div>

{% endblock %}